<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Maens-MacBook-Pro.local" failures="1" tests="3" name="Default test" time="26.282" errors="0" timestamp="2021-11-04T02:32:20 AST">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.14">
    <failure type="java.lang.AssertionError" message="Amount miss match expected [$508,000] but found [$483,000]">
      <![CDATA[java.lang.AssertionError: Amount miss match expected [$508,000] but found [$483,000]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at stepDefinition.TestFeatures.VerifyEstimationAMount(TestFeatures.java:136)
at âœ½.borrowing estimate should be $508,000(src/test/resources/testFeatures/Loan Calculator.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.573"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.761"/>
</testsuite> <!-- Default test -->
